### ISSUE TITLE
打包为Flatpak应用并提交至Flathub分发

### ISSUE THREAD

**Issue by pugaizai** [Riceneeder/electronic-wechat#10]
经由Flathub分发的Flatpak应用便于集中更新，可提供更佳的linux跨发行版体验。
我编写了打包脚本，作者只要复制一下就可以提交到flathub那边就行啦。
https://github.com/NEOVALI/flatpakrepo/tree/main/buildspec/io.github.Riceneeder.electronic-wechat
具体里面的metainfo.xml和后续修改可以作者自己来。脚本已经在本地测试过没问题的

**Comment by Riceneeder** [comment]
可以直接由你发布，我最近在忙事，这个仓库可能会停滞很长一段时间
