### ISSUE TITLE
tput: No value for $TERM and no -T specified

### ISSUE THREAD

**Issue by tyxz888** [Riceneeder/electronic-wechat#5]
==> 正在开始 package()...
tput: No value for $TERM and no -T specified
==> 错误： 在 package() 中发生一个错误。
    正在放弃...

**Comment by Riceneeder** [comment]
~~🤔虽然我没有设置issue template，但不代表提issue不带详细描述我就能解决你的问题吧~~

仓库是有issue template的

**Comment by Kimiblock** [comment]
这个是我在AUR打包的 `electronic-wechat-uos-bin` 么? 如果是的话, 请完全更新系统后再试. 因为在我这里构建完全正常 @tyxz888 

![Screenshot_20221203_152045](https://user-images.githubusercontent.com/61745317/205430641-905c21aa-d28e-495d-aff5-feacfe82a91d.png)


如果还是不行, 那可能是你使用了 Arch 衍生版 / 第三方 AUR助手,  使用yay/makepkg构建或者替换 PKGBUILD 中的 

```
function info() {
	all_off="$(tput sgr0)"
	bold="${all_off}$(tput bold)"
	blue="${bold}$(tput setaf 4)"
	yellow="${bold}$(tput setaf 3)"
    printf "${blue}==>${yellow} [Info]:${bold} $1${all_off}\n"
}
```

为

```
function info() {
        echo $@
}
```

**Comment by Riceneeder** [comment]
@Kimiblock 请问是用的此仓库吗，能方便给个aur链接我放到README里吗

**Comment by Kimiblock** [comment]
> @Kimiblock 请问是用的此仓库吗，能方便给个aur链接我放到README里吗

是的

https://aur.archlinux.org/packages/electronic-wechat-uos-bin

**Comment by Riceneeder** [comment]
> > @Kimiblock 请问是用的此仓库吗，能方便给个aur链接我放到README里吗
> 
> 是的
> 
> https://aur.archlinux.org/packages/electronic-wechat-uos-bin

谢谢，并且欢迎为此仓库贡献代码

**Comment by Riceneeder** [comment]
> ==> 正在开始 package()...
> tput: No value for $TERM and no -T specified
> ==> 错误： 在 package() 中发生一个错误。
>     正在放弃...
> 

问题已解决

**Comment by Kimiblock** [comment]
我猜, 他是用了一个叫 `pamac` 的第三方图形包管理器构建软件包, 看了官方说明这个管理器貌似是自己处理aur包的构建而不是用makepkg...

![Screenshot_20221203_162230](https://user-images.githubusercontent.com/61745317/205431702-c6e686cc-02b5-4624-a023-5eb5d8048690.png)


我装了 `pamac-aur` 也确实复现了, 但包括 `octopi` 图形界面包管理器和其他命令行 AUR 助手都没有问题.

![Screenshot_20221203_162401](https://user-images.githubusercontent.com/61745317/205431766-18741dbd-93f1-4f36-b64d-922518088860.png)

我去 AUR 那边置顶一个评论提醒别人不要用 pamac 安装

**Comment by Riceneeder** [comment]
> 我猜, 他是用了一个叫 `pamac` 的第三方图形包管理器构建软件包, 看了官方说明这个管理器貌似是自己处理aur包的构建而不是用makepkg...
> 我装了 `pamac-aur` 也确实复现了, 但包括 `octopi` 图形界面包管理器和其他命令行 AUR 助手都没有问题.
> 我去 AUR 那边置顶一个评论提醒别人不要用 pamac 安装

好的，感谢您维护并提供aur

**Comment by cool59244768** [comment]
> 这个是我在AUR打包的 `electronic-wechat-uos-bin` 么? 如果是的话, 请完全更新系统后再试. 因为在我这里构建完全正常 @tyxz888
> 
> ![Screenshot_20221203_152045](https://user-images.githubusercontent.com/61745317/205430641-905c21aa-d28e-495d-aff5-feacfe82a91d.png)
> 
> 如果还是不行, 那可能是你使用了 Arch 衍生版 / 第三方 AUR助手, 使用yay/makepkg构建或者替换 PKGBUILD 中的
> 
> ```
> function info() {
> 	all_off="$(tput sgr0)"
> 	bold="${all_off}$(tput bold)"
> 	blue="${bold}$(tput setaf 4)"
> 	yellow="${bold}$(tput setaf 3)"
>     printf "${blue}==>${yellow} [Info]:${bold} $1${all_off}\n"
> }
> ```
> 
> 为
> 
> ```
> function info() {
>         echo $@
> }
> ```

我改了代理，什么招都用了，还是下载超级慢要20多小时？？（我用的小猫咪，上外网很快）愁煞我也

**Comment by Kimiblock** [comment]
@cool59244768  安装 https://aur.archlinux.org/packages/electronic-wechat-uos-bin-cn, 这个包使用了 Onedrive 加速. 只不过我的网站 IP 会因为运营商重新拨号而改变, 所以不太稳定.
![Screenshot_20221208_194543](https://user-images.githubusercontent.com/61745317/206438696-42b13679-adfb-4514-b0a1-4b498522c718.png)
